org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

jei_version=15.20.0.129
jade_file_id=6855440

mod_id=eduhzzepunks_productive_hoe
mod_name=Eduzzepunks Productive Hoe
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.eduhzzepunk.productivehoe
mod_authors=Eduhzzepunk
mod_description=Improves manual farming with smart hoe harvesting, row harvesting, and the Harvester enchantment.
